environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - java -version
  - mvn --version

build_script:
  - mvn clean install

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2